services:
  - type: web
    name: snake-ps9
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: GAME_SERVER_HOST
        value: 127.0.0.1
      - key: GAME_SERVER_PORT
        value: 11000